services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=bookstore'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=admin'
    ports:
      - '5433:5432'
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql