services:
  activemq:
    image: 'symptoma/activemq:latest'
    ports:
      - '8161:8161'
      - '61616:61616'
    environment:
      - ACTIVEMQ_NAME=activemq
      - ACTIVEMQ_USERNAME=admin
      - ACTIVEMQ_PASSWORD=password
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=wallet'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=admin'
    ports:
      - '5434:5432'
