services:
  activemq:
    image: 'symptoma/activemq:latest'
    ports:
      - '8161:8161'
      - '61616:61616'
    environment:
      - ACTIVEMQ_NAME=activemq
      - ACTIVEMQ_USERNAME=admin
      - ACTIVEMQ_PASSWORD=password
